apiVersion: v1
kind: Pod
metadata:
 name: flask-db
 labels:
  app: flask-db
spec:
 containers:
 - name: flask-db-container
   image: nareshm5859/trio-flask-db:latest
   ports:
   - containerPort: 3306
   env:
    - name: MYSQL_ROOT_PASSWORD
      value: naresh
    - name: MYSQL_DATABASE
      value: flask-db

---

apiVersion: v1
kind: Service
metadata:
 name : flask-db
spec:
 selector:
  app: flask-db
 ports:
 - protocol: TCP
   port: 3306
   targetPort: 3306
 type: ClusterIP