apiVersion: v1
kind: Service
metadata:
 name : flask-app
spec:
 selector:
  app: flask-app
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
 type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: nareshm5859/trio-flask-app:latest
        ports:
        - containerPort: 5000