
apiVersion: v1
kind: Service
metadata:
 name : nginx
spec:
 selector:
  app: nginx
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
 type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: nareshm5859/trio-nginx:latest
        ports:
        - containerPort: 80
